version: '3.8'

services:
  # PHP 8.3 with Composer
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_app
    working_dir: /var/www
    volumes:
      - ./app/:/var/www
    depends_on:
      - db
    networks:
      - app-network

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./app/:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-app_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Composer (optional, only needed when running composer commands)
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./app/:/var/www
    working_dir: /var/www
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
